## Project
name: employees
version: "1.0"
config-version: 2
profile: employees

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  employees:
    bronze:
      schema: employees_bronze
      +materialized: view
      +tags: ["bronze"]

## Variables
vars:
  # Global domain for data masking tags
  domain: "employees"
